import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./compontents/NavBar/page";
import Footer from "./compontents/Footer/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <section>{children}</section>
        <Footer />
      </body>
    </html>
  );
}
